language: python
branches:
  only:
  - master
env:
  global:
  - PACKER_VERSION="1.2.2"
  - VAULT_VERSION="0.10.4"
notifications:
  email: false
  slack:
    rooms:
      secure: TODO-change
before_install:
    - sudo apt-get update -y --fix-missing
install:
    - curl -o /tmp/packer.zip -L "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    - sudo unzip -d /usr/local/packer-${PACKER_VERSION} /tmp/packer.zip
    - sudo ln -sf /usr/local/packer-${PACKER_VERSION}/packer /usr/local/bin/packer
    - packer --version
    - sudo apt-get install -y jq
    - pip install awscli ansible --upgrade && aws --version
    - mkdir /tmp/vault
    - wget -q https://releases.hashicorp.com/vault/"$VAULT_VERSION"/vault_"$VAULT_VERSION"_linux_amd64.zip && unzip -d /tmp/vault vault_"$VAULT_VERSION"_linux_amd64.zip
    - export PATH=$PATH:/tmp/vault
    - if [ "$TRAVIS_BRANCH" = "development" ]; then export VAULT_ADDR="$VAULT_ADDR_DEV" VAULT_TOKEN="$VAULT_TOKEN_DEV"; else export VAULT_ADDR="$VAULT_ADDR_DEV" VAULT_TOKEN="$VAULT_TOKEN_DEV"; fi
    - vault --version
script:
    - travis_wait 30 ./build.sh
after_success:
  - "./send-datadog-event.sh agha-ami 'ami,agha'"
